site_name: Nodes-define

theme: readthedocs

nav:
- Home: 'index.md'
- Load Structures:
    - LoadMolecules: 'LoadStructures/N1.md'
- Compute: 
    - Geometry Optimization: 'Compute/N101.md'
    - Docking: 'Compute/N102.md'
    - Complex Search: 'Compute/N103.md'
